//+------------------------------------------------------------------+
//|                                              GapDriveCore.mqh    |
//|                     Gap Drive EA — Core Engine Header            |
//+------------------------------------------------------------------+
#ifndef GAPDRIVE_CORE_MQH
#define GAPDRIVE_CORE_MQH

#include <Trade\Trade.mqh>

//+------------------------------------------------------------------+
//| Enumerations                                                      |
//+------------------------------------------------------------------+

enum GAP_STATE
{
   WAITING_FOR_GAP,
   GAP_DETECTED,
   WAITING_ENTRY,
   TRADE_ACTIVE,
   TRADE_FINISHED,
   EXPIRED
};

enum ENTRY_MODE
{
   ENTRY_REFERENCE = 0,   // Uses original trigger level
   ENTRY_RR_OFFSET = 1    // Uses calculated RR offset entry
};

enum STOP_MODE
{
   STOP_SYMMETRIC          = 0,   // Mirrored stop (gap size distance)
   STOP_SECOND_CANDLE_EXTREME = 1 // Extends SL to second candle wick if beyond symmetric
};

enum REVERSAL_TARGET
{
   TARGET_REFERENCE = 0,  // Reversal targets reference gap edge
   TARGET_GAP_FILL  = 1   // Reversal targets full gap fill
};

enum ENUM_LOT_MODE
{
   LOT_MODE_FIXED,          // Fixed Lot Size
   LOT_MODE_PERCENT,        // % of Account Capital (Risk-based per Stop Loss)
   LOT_MODE_TARGET_PROFIT   // Auto-calculate to win $X on Take Profit
};

//+------------------------------------------------------------------+
//| Per-setup structure                                               |
//+------------------------------------------------------------------+
struct GapSetup
{
   datetime   gap_time;          // Timestamp of the gap candle (second reference candle)
   bool       bullish_gap;       // True = gap down → BUY setup
   bool       bearish_gap;       // True = gap up  → SELL setup
   double     trigger_price;     // Effective entry price (may be RR-repositioned)
   double     stop_price;        // Stop loss price
   double     target_price;      // Take profit price
   double     reference_entry;   // Original reference entry (gap edge)
   double     gap_top;           // Top of the gap zone
   double     gap_bottom;        // Bottom of the gap zone
   double     gap_size;          // gap_top - gap_bottom
   bool       triggered;         // True once price touched trigger_price
   bool       finished;          // True once trade closed (TP or SL hit)
   bool       expired;           // True once expiration window elapsed without trigger
   ulong      position_ticket;   // MT5 position ticket (0 if none)
   GAP_STATE  state;             // Current state machine state
   int        gap_bar_index;     // Absolute bar index at detection time (rates_total basis)
   bool       is_reversal;       // True if this setup was generated by the reversal module
};

//+------------------------------------------------------------------+
//| Statistics structure                                              |
//+------------------------------------------------------------------+
struct StatsBlock
{
   int   detected;
   int   triggered;
   int   wins;
   int   losses;
   int   expired;
};

//+------------------------------------------------------------------+
//| MODULE: Gap bar time check                                        |
//| Returns true if barTime matches the configured gap hour/minute    |
//+------------------------------------------------------------------+
bool IsGapBar(const datetime barTime, const int gapHour, const int gapMinute)
{
   MqlDateTime dt;
   TimeToStruct(barTime, dt);
   return (dt.hour == gapHour && dt.min == gapMinute);
}

//+------------------------------------------------------------------+
//| MODULE: Gap body calculation                                      |
//| Uses MAX(Open,Close) and MIN(Open,Close) — body only, not wicks  |
//| Returns false if no gap exists between the two candle bodies      |
//| isLong = true  → gap down  → BUY  setup                         |
//| isLong = false → gap up    → SELL setup                         |
//+------------------------------------------------------------------+
bool CalcGap(const double openPrev,  const double closePrev,
             const double openCurr,  const double closeCurr,
             double      &gapTop,    double &gapBottom,
             bool        &isLong)
{
   const double bodyTopPrev    = MathMax(openPrev,  closePrev);
   const double bodyBottomPrev = MathMin(openPrev,  closePrev);
   const double bodyTopCurr    = MathMax(openCurr,  closeCurr);
   const double bodyBottomCurr = MathMin(openCurr,  closeCurr);

   // GAP DOWN: current body entirely below previous body → BUY
   if(bodyBottomCurr < bodyBottomPrev && bodyTopCurr < bodyBottomPrev)
   {
      gapTop    = bodyTopPrev;
      gapBottom = bodyTopCurr;
      isLong    = true;
      return (gapTop > gapBottom);
   }

   // GAP UP: current body entirely above previous body → SELL
   if(bodyBottomCurr > bodyTopPrev && bodyTopCurr > bodyTopPrev)
   {
      gapBottom = bodyBottomPrev;
      gapTop    = bodyBottomCurr;
      isLong    = false;
      return (gapTop > gapBottom);
   }

   return false;
}

//+------------------------------------------------------------------+
//| MODULE: True gap wick filter                                      |
//| Returns false if the wick-based gap fails requirements            |
//+------------------------------------------------------------------+
bool PassesTrueGapFilter(const bool   isLong,
                         const double highPrev,  const double lowPrev,
                         const double highCurr,  const double lowCurr,
                         const double minTrueGapPoints)
{
   if(isLong)
   {
      // Gap down: current wick high must be below previous wick low
      if(highCurr >= lowPrev)
         return false;
      double trueGapSize = (lowPrev - highCurr) / _Point;
      return (trueGapSize >= minTrueGapPoints);
   }
   else
   {
      // Gap up: current wick low must be above previous wick high
      if(lowCurr <= highPrev)
         return false;
      double trueGapSize = (lowCurr - highPrev) / _Point;
      return (trueGapSize >= minTrueGapPoints);
   }
}

//+------------------------------------------------------------------+
//| MODULE: Gap size validation                                       |
//+------------------------------------------------------------------+
bool ValidateGap(const double gapSizePoints,
                 const double minGapPoints,
                 const double maxGapPoints)
{
   return (gapSizePoints >= minGapPoints && gapSizePoints <= maxGapPoints);
}

//+------------------------------------------------------------------+
//| MODULE: Level generation (entry, stop, target)                   |
//| stopMode controls whether SL uses second candle extreme          |
//+------------------------------------------------------------------+
void GenerateLevels(const double    gapTop,
                    const double    gapBottom,
                    const double    gapSize,
                    const bool      isLong,
                    const double    gapCandleHigh,
                    const double    gapCandleLow,
                    const STOP_MODE stopMode,
                    double         &outEntry,
                    double         &outStop,
                    double         &outTarget)
{
   if(isLong)
   {
      // GAP DOWN — BUY SETUP
      outEntry  = gapBottom;
      outTarget = gapTop;
      outStop   = gapBottom - gapSize;   // symmetric

      // STOP_SECOND_CANDLE_EXTREME: extend SL if gap candle low is lower
      if(stopMode == STOP_SECOND_CANDLE_EXTREME)
      {
         if(gapCandleLow < outStop)
            outStop = gapCandleLow;
      }
   }
   else
   {
      // GAP UP — SELL SETUP
      outEntry  = gapTop;
      outTarget = gapBottom;
      outStop   = gapTop + gapSize;      // symmetric

      // STOP_SECOND_CANDLE_EXTREME: extend SL if gap candle high is higher
      if(stopMode == STOP_SECOND_CANDLE_EXTREME)
      {
         if(gapCandleHigh > outStop)
            outStop = gapCandleHigh;
      }
   }
}

//+------------------------------------------------------------------+
//| MODULE: RR-based entry repositioning                              |
//| Repositions entry so that Reward / Risk = desiredRR              |
//| Formula: entry = stop + distance * (1 / (RR + 1))               |
//+------------------------------------------------------------------+
double CalculateRRBasedEntry(const bool   isBuy,
                             const double stopPrice,
                             const double targetPrice,
                             const double desiredRR)
{
   const double distance     = MathAbs(targetPrice - stopPrice);
   const double entryPercent = 1.0 / (desiredRR + 1.0);

   if(isBuy)
      return stopPrice + distance * entryPercent;
   else
      return stopPrice - distance * entryPercent;
}

//+------------------------------------------------------------------+
//| MODULE: Validate RR-repositioned entry is between SL and TP      |
//+------------------------------------------------------------------+
bool ValidateRREntry(const bool   isLong,
                     const double rrEntry,
                     const double stopPrice,
                     const double targetPrice)
{
   if(isLong)
      return (rrEntry > stopPrice && rrEntry < targetPrice);
   else
      return (rrEntry < stopPrice && rrEntry > targetPrice);
}

//+------------------------------------------------------------------+
//| MODULE: Volume normalization                                      |
//| Rounds down to SYMBOL_VOLUME_STEP and clamps to min/max           |
//+------------------------------------------------------------------+
double NormalizeVolumeBySymbol(const string symbol, const double volumeRaw)
{
   double vmin = 0.0, vmax = 0.0, vstep = 0.0;
   if(!SymbolInfoDouble(symbol, SYMBOL_VOLUME_MIN, vmin) ||
      !SymbolInfoDouble(symbol, SYMBOL_VOLUME_MAX, vmax) ||
      !SymbolInfoDouble(symbol, SYMBOL_VOLUME_STEP, vstep))
   {
      PrintFormat("GapDriveEA: Lot calc failed (symbol volume specs missing) | %s", symbol);
      return 0.0;
   }

   if(vmin <= 0.0 || vmax <= 0.0 || vstep <= 0.0 || vmax < vmin)
   {
      PrintFormat("GapDriveEA: Lot calc failed (invalid volume constraints) | %s | min=%.8f max=%.8f step=%.8f",
                  symbol, vmin, vmax, vstep);
      return 0.0;
   }

   double v = volumeRaw;
   if(v <= 0.0)
      return 0.0;

   // Round down to step (conservative)
   v = MathFloor(v / vstep) * vstep;

   // Clamp
   if(v < vmin) v = vmin;
   if(v > vmax) v = vmax;

   // Derive required precision from volume step (e.g., 0.01 -> 2 digits)
   int digits = 0;
   double step = vstep;
   while(digits < 8 && step > 0.0 && step < 1.0 && MathAbs(step - MathRound(step)) > 1e-12)
   {
      step *= 10.0;
      digits++;
   }

   return NormalizeDouble(v, digits);
}

//+------------------------------------------------------------------+
//| MODULE: Money Management lot sizing                               |
//| entryPrice/stopPrice/targetPrice are the logical setup prices     |
//+------------------------------------------------------------------+
double CalculateLotSize(const string        symbol,
                        const ENUM_LOT_MODE lotMode,
                        const double        fixedLot,
                        const double        riskPercent,
                        const double        targetProfitUsd,
                        const double        entryPrice,
                        const double        stopPrice,
                        const double        targetPrice)
{
   if(symbol == NULL || symbol == "")
   {
      Print("GapDriveEA: Lot calc failed (empty symbol)");
      return 0.0;
   }

   if(lotMode == LOT_MODE_FIXED)
      return NormalizeVolumeBySymbol(symbol, fixedLot);

   double tickSize = 0.0, tickValue = 0.0;
   if(!SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_SIZE, tickSize) ||
      !SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_VALUE, tickValue))
   {
      PrintFormat("GapDriveEA: Lot calc failed (tick specs missing) | %s", symbol);
      return 0.0;
   }

   if(tickSize <= 0.0 || tickValue <= 0.0)
   {
      PrintFormat("GapDriveEA: Lot calc failed (invalid tick specs) | %s | tickSize=%.10f tickValue=%.10f",
                  symbol, tickSize, tickValue);
      return 0.0;
   }

   double distance = 0.0;
   double moneyGoal = 0.0;

   if(lotMode == LOT_MODE_PERCENT)
   {
      distance = MathAbs(entryPrice - stopPrice);
      if(distance <= 0.0)
      {
         PrintFormat("GapDriveEA: Lot calc failed (zero SL distance) | entry=%.5f sl=%.5f", entryPrice, stopPrice);
         return 0.0;
      }

      if(riskPercent <= 0.0)
      {
         PrintFormat("GapDriveEA: Lot calc failed (riskPercent <= 0) | risk=%.4f", riskPercent);
         return 0.0;
      }

      const double balance = AccountInfoDouble(ACCOUNT_BALANCE);
      if(balance <= 0.0)
      {
         Print("GapDriveEA: Lot calc failed (balance <= 0)");
         return 0.0;
      }
      moneyGoal = balance * (riskPercent / 100.0);
   }
   else if(lotMode == LOT_MODE_TARGET_PROFIT)
   {
      distance = MathAbs(targetPrice - entryPrice);
      if(distance <= 0.0)
      {
         PrintFormat("GapDriveEA: Lot calc failed (zero TP distance) | entry=%.5f tp=%.5f", entryPrice, targetPrice);
         return 0.0;
      }
      if(targetProfitUsd <= 0.0)
      {
         PrintFormat("GapDriveEA: Lot calc failed (targetProfitUsd <= 0) | target=%.2f", targetProfitUsd);
         return 0.0;
      }
      moneyGoal = targetProfitUsd;
   }
   else
   {
      PrintFormat("GapDriveEA: Lot calc failed (unknown lot mode) | %d", (int)lotMode);
      return 0.0;
   }

   const double distanceTicks = distance / tickSize;
   if(distanceTicks <= 0.0)
   {
      PrintFormat("GapDriveEA: Lot calc failed (distanceTicks <= 0) | dist=%.10f tickSize=%.10f",
                  distance, tickSize);
      return 0.0;
   }

   const double moneyPerLot = distanceTicks * tickValue;
   if(moneyPerLot <= 0.0)
   {
      PrintFormat("GapDriveEA: Lot calc failed (moneyPerLot <= 0) | ticks=%.4f tickValue=%.10f",
                  distanceTicks, tickValue);
      return 0.0;
   }

   const double rawLot = moneyGoal / moneyPerLot;
   return NormalizeVolumeBySymbol(symbol, rawLot);
}

#endif // GAPDRIVE_CORE_MQH
